### ISSUE TITLE
MIOpen dependency recipes are broken

### ISSUE THREAD

**Issue by tmarplatt** [pfultz2/rocm-recipes#4]
The MIOpen dependency recipes are pointing to broken URLs ([Example](https://github.com/ROCmSoftwarePlatform/rocm-recipes/blob/master/miopen/boost/1.72/package.txt)) because the [ginger.amd.com](http://ginger.amd.com) file repository is down.

Fortunately, all matching dependencies found under `recipes/` are using working URLs from official sources with matching hashes. The broken URLs can be replaced with those. I've collected them here:

```
https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2
https://downloads.sourceforge.net/project/bzip2/bzip2-1.0.6.tar.gz
https://sqlite.org/2017/sqlite-autoconf-3170000.tar.gz
http://www.zlib.net/zlib-1.2.12.tar.gz
```

**Comment by junliume** [comment]
issue fixed and alternative external locations are set
